// Styles
import '@/styles/globals.css'

// Speed Insights

import { SpeedInsights } from '@vercel/speed-insights/next'

// Fonts

import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'
import { JetBrains_Mono } from 'next/font/google'

// Metadata

import type { Metadata } from 'next'

// Environment Variables

import { env } from '@/env'

// PostHog

import { PHProvider } from './providers'
import dynamic from 'next/dynamic'

// Next-themes

import { ThemeProvider } from '@/components/theme/ThemeProvider'
import { ThemeToggle } from '@/components/theme/ThemeToggle'
import { useTheme } from 'next-themes'

// Clerk

import {
	ClerkProvider,
	SignInButton,
	SignedIn,
	SignedOut,
	UserButton,
} from '@clerk/nextjs'

import { auth, currentUser } from '@clerk/nextjs/server'
import posthog from 'posthog-js'

// Dynamic imports

const PostHogPageView = dynamic(() => import('./PostHogPageView'), {
	ssr: false,
})

// Fonts

const jetbrains = JetBrains_Mono({
	weight: 'variable',
	subsets: ['latin'],
	fallback: ['monospace'],
})

// Metadata

export const metadata: Metadata = {
	title: 'Create T3 App',
	description: 'Generated by create-t3-app',
	icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default async function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	const { userId } = auth()

	if (userId) {
		const user = await currentUser()
		posthog.identify(userId, {
			email: user?.emailAddresses[0]?.emailAddress,
			userId: userId,
		})
	}

	return (
		<ClerkProvider>
			<PHProvider>
				<html
					lang="en"
					className={`${GeistSans.variable} ${GeistMono.variable} ${jetbrains.className}`}
					suppressHydrationWarning={true}
				>
					<head />

					<body>
						<ThemeProvider
							attribute="class"
							defaultTheme={'system'}
						>
							<header className="flex flex-row items-stretch justify-between px-2 py-2 scroll-m-0">
								<SignedOut>
									<SignInButton />
								</SignedOut>
								<SignedIn>
									<UserButton />
								</SignedIn>

								<ThemeToggle />
							</header>
							<main className="">
								{children}
								<PostHogPageView />
								<SpeedInsights />
							</main>
							<footer></footer>
						</ThemeProvider>
					</body>
				</html>
			</PHProvider>
		</ClerkProvider>
	)
}
